swagger: '2.0'
#必要字段！描述API接口信息的元数据
info:
#版本号
version:  0.0.1
#接口标题
title: RESTful接口
#接口文档的描述
description: RESTful API
termsOfService: ""
contact:
name: 付红竹

host: localhost:18090
basePath: /cms
schemes:
  - https
  - http

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  APIToken:
    type: apiKey
    in: header
    name: X-API-TOKEN

security:
  - APIToken: []

definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      data:
        type: string
      message:
        type: string


  ErrorResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      data:
        type: string

  CustomUser:
    properties:
      user_login:
        type: string
        description: 用户帐号
      user_pass:
        type: string
        description: 密码
      new_pass:
        type: string
        description: 新密码
      captcha:
        type: string
        description: 验证码
      level:
        type: integer
        description: 客服级别
      real_name:
        type: string
        description: 真实姓名
      sex:
        type: integer
        description: 性别
      mobile:
        type: string
        description: 手机号
      card:
        type: string
        description: 身份证号
      company:
        type: string
        description: 公司
      area:
        type: array
        items:
          properties:
            area_province:
              type: string
            area_city:
              type: string
            area_country:
              type: string
            places:
              type: string


paths:
  /custom/user:
    post:
      tags:
        - 用户接口
      summary: 用户创建
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/CustomUser'
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/ApiResponse'
        default:
          description: 操作异常,执行失败.返回信息描述错误详情
          schema:
            $ref: '#/definitions/ErrorResponse'


